<?php

namespace App\Support;

use App\Enums\StudyRegion;

class StudyRegionResolver
{
    private const COUNTRY_TO_REGION = [
        'Japan' => StudyRegion::ASIA,
        'China' => StudyRegion::ASIA,
        'India' => StudyRegion::ASIA,
        'Thailand' => StudyRegion::ASIA,
        'Vietnam' => StudyRegion::ASIA,
        'South Korea' => StudyRegion::ASIA,

        'France' => StudyRegion::EUROPE,
        'Germany' => StudyRegion::EUROPE,
        'Italy' => StudyRegion::EUROPE,
        'Spain' => StudyRegion::EUROPE,
        'United Kingdom' => StudyRegion::EUROPE,

        'Egypt' => StudyRegion::AFRICA,
        'Kenya' => StudyRegion::AFRICA,
        'South Africa' => StudyRegion::AFRICA,
        'Morocco' => StudyRegion::AFRICA,
        'Ethiopia' => StudyRegion::AFRICA,

        'Canada' => StudyRegion::NORTH_AMERICA,
        'United States' => StudyRegion::NORTH_AMERICA,
        'Mexico' => StudyRegion::NORTH_AMERICA,
        'Guatemala' => StudyRegion::NORTH_AMERICA,
        'Panama' => StudyRegion::NORTH_AMERICA,

        'Ecuador' => StudyRegion::SOUTH_AMERICA,
        'Brazil' => StudyRegion::SOUTH_AMERICA,
        'Argentina' => StudyRegion::SOUTH_AMERICA,
        'Peru' => StudyRegion::SOUTH_AMERICA,
        'Chile' => StudyRegion::SOUTH_AMERICA,
        'Colombia' => StudyRegion::SOUTH_AMERICA,

        'Australia' => StudyRegion::OCEANIA,
        'New Zealand' => StudyRegion::OCEANIA,
        'Fiji' => StudyRegion::OCEANIA,
        'Papua New Guinea' => StudyRegion::OCEANIA,

        'Andorra' => StudyRegion::EUROPE,
        'United Arab Emirates' => StudyRegion::ASIA,
        'Afghanistan' => StudyRegion::ASIA,
        'Antigua and Barbuda' => StudyRegion::NORTH_AMERICA,
        'Anguilla' => StudyRegion::NORTH_AMERICA,
        'Albania' => StudyRegion::EUROPE,
        'Armenia' => StudyRegion::ASIA,
        'Angola' => StudyRegion::AFRICA,
        'Antarctica' => StudyRegion::UNKNOWN,
        'American Samoa' => StudyRegion::OCEANIA,
        'Austria' => StudyRegion::EUROPE,
        'Aruba' => StudyRegion::NORTH_AMERICA,
        'Aland Islands' => StudyRegion::EUROPE,
        'Azerbaijan' => StudyRegion::ASIA,
        'Bosnia and Herzegovina' => StudyRegion::EUROPE,
        'Barbados' => StudyRegion::NORTH_AMERICA,
        'Bangladesh' => StudyRegion::ASIA,
        'Belgium' => StudyRegion::EUROPE,
        'Burkina Faso' => StudyRegion::AFRICA,
        'Bulgaria' => StudyRegion::EUROPE,
        'Bahrain' => StudyRegion::ASIA,
        'Burundi' => StudyRegion::AFRICA,
        'Benin' => StudyRegion::AFRICA,
        'Saint Barthelemy' => StudyRegion::NORTH_AMERICA,
        'Bermuda' => StudyRegion::NORTH_AMERICA,
        'Brunei' => StudyRegion::ASIA,
        'Bolivia' => StudyRegion::SOUTH_AMERICA,
        'Caribbean Netherlands' => StudyRegion::NORTH_AMERICA,
        'Bahamas' => StudyRegion::NORTH_AMERICA,
        'Bhutan' => StudyRegion::ASIA,
        'Bouvet Island' => StudyRegion::UNKNOWN,
        'Botswana' => StudyRegion::AFRICA,
        'Belarus' => StudyRegion::EUROPE,
        'Belize' => StudyRegion::NORTH_AMERICA,
        'Cocos (Keeling) Islands' => StudyRegion::OCEANIA,
        'Democratic Republic of the Congo' => StudyRegion::AFRICA,
        'Central African Republic' => StudyRegion::AFRICA,
        'Republic of the Congo' => StudyRegion::AFRICA,
        'Switzerland' => StudyRegion::EUROPE,
        "Cote d'Ivoire" => StudyRegion::AFRICA,
        'Cook Islands' => StudyRegion::OCEANIA,
        'Cameroon' => StudyRegion::AFRICA,
        'Costa Rica' => StudyRegion::NORTH_AMERICA,
        'Cuba' => StudyRegion::NORTH_AMERICA,
        'Cape Verde' => StudyRegion::AFRICA,
        'Curacao' => StudyRegion::NORTH_AMERICA,
        'Christmas Island' => StudyRegion::OCEANIA,
        'Cyprus' => StudyRegion::ASIA,
        'Czech Republic' => StudyRegion::EUROPE,
        'Djibouti' => StudyRegion::AFRICA,
        'Denmark' => StudyRegion::EUROPE,
        'Dominica' => StudyRegion::NORTH_AMERICA,
        'Dominican Republic' => StudyRegion::NORTH_AMERICA,
        'Algeria' => StudyRegion::AFRICA,
        'Estonia' => StudyRegion::EUROPE,
        'Western Sahara' => StudyRegion::AFRICA,
        'Eritrea' => StudyRegion::AFRICA,
        'Finland' => StudyRegion::EUROPE,
        'Falkland Islands' => StudyRegion::SOUTH_AMERICA,
        'Federated States of Micronesia' => StudyRegion::OCEANIA,
        'Faroe Islands' => StudyRegion::EUROPE,
        'Gabon' => StudyRegion::AFRICA,
        'Grenada' => StudyRegion::NORTH_AMERICA,
        'Georgia' => StudyRegion::ASIA,
        'French Guiana' => StudyRegion::SOUTH_AMERICA,
        'Guernsey' => StudyRegion::EUROPE,
        'Ghana' => StudyRegion::AFRICA,
        'Gibraltar' => StudyRegion::EUROPE,
        'Greenland' => StudyRegion::NORTH_AMERICA,
        'Gambia' => StudyRegion::AFRICA,
        'Guinea' => StudyRegion::AFRICA,
        'Guadeloupe' => StudyRegion::NORTH_AMERICA,
        'Equatorial Guinea' => StudyRegion::AFRICA,
        'Greece' => StudyRegion::EUROPE,
        'South Georgia and the South Sandwich Islands' => StudyRegion::UNKNOWN,
        'Guam' => StudyRegion::OCEANIA,
        'Guinea-Bissau' => StudyRegion::AFRICA,
        'Guyana' => StudyRegion::SOUTH_AMERICA,
        'Hong Kong' => StudyRegion::ASIA,
        'Heard Island and McDonald Islands' => StudyRegion::UNKNOWN,
        'Honduras' => StudyRegion::NORTH_AMERICA,
        'Croatia' => StudyRegion::EUROPE,
        'Haiti' => StudyRegion::NORTH_AMERICA,
        'Hungary' => StudyRegion::EUROPE,
        'Indonesia' => StudyRegion::ASIA,
        'Ireland' => StudyRegion::EUROPE,
        'Israel' => StudyRegion::ASIA,
        'Isle of Man' => StudyRegion::EUROPE,
        'British Indian Ocean Territory' => StudyRegion::ASIA,
        'Iraq' => StudyRegion::ASIA,
        'Iran' => StudyRegion::ASIA,
        'Iceland' => StudyRegion::EUROPE,
        'Jersey' => StudyRegion::EUROPE,
        'Jamaica' => StudyRegion::NORTH_AMERICA,
        'Jordan' => StudyRegion::ASIA,
        'Kyrgyzstan' => StudyRegion::ASIA,
        'Cambodia' => StudyRegion::ASIA,
        'Kiribati' => StudyRegion::OCEANIA,
        'Comoros' => StudyRegion::AFRICA,
        'Saint Kitts and Nevis' => StudyRegion::NORTH_AMERICA,
        'North Korea' => StudyRegion::ASIA,
        'Kuwait' => StudyRegion::ASIA,
        'Cayman Islands' => StudyRegion::NORTH_AMERICA,
        'Kazakhstan' => StudyRegion::ASIA,
        'Laos' => StudyRegion::ASIA,
        'Lebanon' => StudyRegion::ASIA,
        'Saint Lucia' => StudyRegion::NORTH_AMERICA,
        'Liechtenstein' => StudyRegion::EUROPE,
        'Sri Lanka' => StudyRegion::ASIA,
        'Liberia' => StudyRegion::AFRICA,
        'Lesotho' => StudyRegion::AFRICA,
        'Lithuania' => StudyRegion::EUROPE,
        'Luxembourg' => StudyRegion::EUROPE,
        'Latvia' => StudyRegion::EUROPE,
        'Libya' => StudyRegion::AFRICA,
        'Monaco' => StudyRegion::EUROPE,
        'Moldova' => StudyRegion::EUROPE,
        'Montenegro' => StudyRegion::EUROPE,
        'Saint Martin' => StudyRegion::NORTH_AMERICA,
        'Madagascar' => StudyRegion::AFRICA,
        'Marshall Islands' => StudyRegion::OCEANIA,
        'North Macedonia' => StudyRegion::EUROPE,
        'Mali' => StudyRegion::AFRICA,
        'Myanmar' => StudyRegion::ASIA,
        'Mongolia' => StudyRegion::ASIA,
        'Macao' => StudyRegion::ASIA,
        'Northern Mariana Islands' => StudyRegion::OCEANIA,
        'Martinique' => StudyRegion::NORTH_AMERICA,
        'Mauritania' => StudyRegion::AFRICA,
        'Montserrat' => StudyRegion::NORTH_AMERICA,
        'Malta' => StudyRegion::EUROPE,
        'Mauritius' => StudyRegion::AFRICA,
        'Maldives' => StudyRegion::ASIA,
        'Malawi' => StudyRegion::AFRICA,
        'Malaysia' => StudyRegion::ASIA,
        'Mozambique' => StudyRegion::AFRICA,
        'Namibia' => StudyRegion::AFRICA,
        'New Caledonia' => StudyRegion::OCEANIA,
        'Niger' => StudyRegion::AFRICA,
        'Norfolk Island' => StudyRegion::OCEANIA,
        'Nigeria' => StudyRegion::AFRICA,
        'Nicaragua' => StudyRegion::NORTH_AMERICA,
        'Netherlands' => StudyRegion::EUROPE,
        'Norway' => StudyRegion::EUROPE,
        'Nepal' => StudyRegion::ASIA,
        'Nauru' => StudyRegion::OCEANIA,
        'Niue' => StudyRegion::OCEANIA,
        'Oman' => StudyRegion::ASIA,
        'French Polynesia' => StudyRegion::OCEANIA,
        'Philippines' => StudyRegion::ASIA,
        'Pakistan' => StudyRegion::ASIA,
        'Poland' => StudyRegion::EUROPE,
        'Saint Pierre and Miquelon' => StudyRegion::NORTH_AMERICA,
        'Pitcairn Islands' => StudyRegion::OCEANIA,
        'Puerto Rico' => StudyRegion::NORTH_AMERICA,
        'Palestine' => StudyRegion::ASIA,
        'Portugal' => StudyRegion::EUROPE,
        'Palau' => StudyRegion::OCEANIA,
        'Paraguay' => StudyRegion::SOUTH_AMERICA,
        'Qatar' => StudyRegion::ASIA,
        'Reunion' => StudyRegion::AFRICA,
        'Romania' => StudyRegion::EUROPE,
        'Serbia' => StudyRegion::EUROPE,
        'Russia' => StudyRegion::EUROPE,
        'Rwanda' => StudyRegion::AFRICA,
        'Saudi Arabia' => StudyRegion::ASIA,
        'Solomon Islands' => StudyRegion::OCEANIA,
        'Seychelles' => StudyRegion::AFRICA,
        'Sudan' => StudyRegion::AFRICA,
        'Sweden' => StudyRegion::EUROPE,
        'Singapore' => StudyRegion::ASIA,
        'Saint Helena' => StudyRegion::AFRICA,
        'Slovenia' => StudyRegion::EUROPE,
        'Svalbard and Jan Mayen' => StudyRegion::EUROPE,
        'Slovakia' => StudyRegion::EUROPE,
        'Sierra Leone' => StudyRegion::AFRICA,
        'San Marino' => StudyRegion::EUROPE,
        'Senegal' => StudyRegion::AFRICA,
        'Somalia' => StudyRegion::AFRICA,
        'Suriname' => StudyRegion::SOUTH_AMERICA,
        'South Sudan' => StudyRegion::AFRICA,
        'Sao Tome and Principe' => StudyRegion::AFRICA,
        'El Salvador' => StudyRegion::NORTH_AMERICA,
        'Sint Maarten' => StudyRegion::NORTH_AMERICA,
        'Syria' => StudyRegion::ASIA,
        'Eswatini' => StudyRegion::AFRICA,
        'Turks and Caicos Islands' => StudyRegion::NORTH_AMERICA,
        'Chad' => StudyRegion::AFRICA,
        'French Southern Territories' => StudyRegion::UNKNOWN,
        'Togo' => StudyRegion::AFRICA,
        'Tajikistan' => StudyRegion::ASIA,
        'Tokelau' => StudyRegion::OCEANIA,
        'Timor-Leste' => StudyRegion::ASIA,
        'Turkmenistan' => StudyRegion::ASIA,
        'Tunisia' => StudyRegion::AFRICA,
        'Tonga' => StudyRegion::OCEANIA,
        'Turkey' => StudyRegion::ASIA,
        'Trinidad and Tobago' => StudyRegion::NORTH_AMERICA,
        'Tuvalu' => StudyRegion::OCEANIA,
        'Taiwan' => StudyRegion::ASIA,
        'Tanzania' => StudyRegion::AFRICA,
        'Ukraine' => StudyRegion::EUROPE,
        'Uganda' => StudyRegion::AFRICA,
        'United States Minor Outlying Islands' => StudyRegion::OCEANIA,
        'Uruguay' => StudyRegion::SOUTH_AMERICA,
        'Uzbekistan' => StudyRegion::ASIA,
        'Vatican City' => StudyRegion::EUROPE,
        'Saint Vincent and the Grenadines' => StudyRegion::NORTH_AMERICA,
        'Venezuela' => StudyRegion::SOUTH_AMERICA,
        'British Virgin Islands' => StudyRegion::NORTH_AMERICA,
        'United States Virgin Islands' => StudyRegion::NORTH_AMERICA,
        'Vanuatu' => StudyRegion::OCEANIA,
        'Wallis and Futuna' => StudyRegion::OCEANIA,
        'Samoa' => StudyRegion::OCEANIA,
        'Yemen' => StudyRegion::ASIA,
        'Mayotte' => StudyRegion::AFRICA,
        'Zambia' => StudyRegion::AFRICA,
        'Zimbabwe' => StudyRegion::AFRICA,
    ];

    public static function resolve(?string $country): StudyRegion
    {
        if ($country === null) {
            return StudyRegion::UNKNOWN;
        }

        $normalized = trim($country);
        if ($normalized === '') {
            return StudyRegion::UNKNOWN;
        }

        return self::COUNTRY_TO_REGION[$normalized] ?? StudyRegion::UNKNOWN;
    }
}