name: PR Labeler
on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  labeler:
    timeout-minutes: 1
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
          sync-labels: false
