<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class WorldHeritageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $sites = [
            [
                'id' => 1133,
                'official_name' => 'Ancient and Primeval Beech Forests of the Carpathians and Other Regions of Europe',
                'name' => 'Ancient and Primeval Beech Forests',
                'name_jp' => 'カルパティア山脈とヨーロッパ各地の古代及び原生ブナ林',
                'country' => 'Slovakia',
                'region' => 'Europe',
                'state_party' => null,
                'category' => 'Natural',
                'criteria' => json_encode(['ix']),
                'year_inscribed' => 2007,
                'area_hectares' => 99947.81,
                'buffer_zone_hectares' => 296275.8,
                'is_endangered' => false,
                'latitude' => 0.0,
                'longitude' => 0.0,
                'short_description' => '氷期後のブナの自然拡散史を示すヨーロッパ各地の原生的ブナ林群から成る越境・連続資産。',
                'image_url' => '',
                'unesco_site_url' => 'https://whc.unesco.org/en/list/1133',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 1442,
                'official_name' => "Silk Roads: the Routes Network of Chang'an-Tianshan Corridor",
                'name' => "Silk·Roads:·Chang'an–Tianshan·Corridor",
                'name_jp' => 'シルクロード：長安－天山回廊の交易路網',
                'country' => 'China',
                'region' => 'Asia',
                'state_party' => null,
                'category' => 'Cultural',
                'criteria' => json_encode(['ii','iii','vi']),
                'year_inscribed' => 2014,
                'area_hectares' => 42668.16,
                'buffer_zone_hectares' => 189963.1,
                'is_endangered' => false,
                'latitude' => 0.0,
                'longitude' => 0.0,
                'short_description' => '中国・カザフスタン・キルギスにまたがるオアシス都市や遺跡群で構成され、東西交流の歴史を物証する文化遺産群。',
                'image_url' => '',
                'unesco_site_url' => 'https://whc.unesco.org/en/list/1442',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 1662,
                'official_name' => 'Silk Roads: Zarafshan-Karakum Corridor',
                'name' => 'Silk Roads: Zarafshan-Karakum Corridor',
                'name_jp' => 'シルクロード：ザラフシャン-カラクム回廊',
                'country' => 'Tajikistan',
                'region' => 'Asia',
                'state_party' => null,
                'category' => 'Cultural',
                'criteria' => json_encode(['ii','iii']),
                'year_inscribed' => 2023,
                'area_hectares' => 0.0,
                'buffer_zone_hectares' => null,
                'is_endangered' => false,
                'latitude' => 0.0,
                'longitude' => 0.0,
                'short_description' => '中央アジアのザラフシャン谷からカラクム砂漠にかけて展開するオアシス都市・交易遺跡群の連続資産。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/1662',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 661,
                'official_name' => 'Himeji-jo',
                'name' => 'Himeji-jo',
                'name_jp' => '姫路城',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Cultural',
                'criteria' => json_encode(['i','iv']),
                'year_inscribed' => 1993,
                'area_hectares' => 107.0,
                'buffer_zone_hectares' => 143.0,
                'is_endangered' => false,
                'latitude' => 34.8394,
                'longitude' => 134.6939,
                'short_description' => '白鷺城の名で知られる城郭建築の傑作。天守群と縄張りが良好に保存される。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/661',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 688,
                'official_name' => 'Historic Monuments of Ancient Kyoto (Kyoto, Uji and Otsu Cities)',
                'name' => 'Historic Monuments of Ancient Kyoto',
                'name_jp' => '古都京都の文化財',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Cultural',
                'criteria' => json_encode(['ii','iv']),
                'year_inscribed' => 1994,
                'area_hectares' => 1056.0,
                'buffer_zone_hectares' => 3579.0,
                'is_endangered' => false,
                'latitude' => null,
                'longitude' => null,
                'short_description' => '京都・宇治・大津に点在する社寺・庭園・城郭などから成る文化遺産群。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/688',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 662,
                'official_name' => 'Yakushima',
                'name' => 'Yakushima',
                'name_jp' => '屋久島',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Natural',
                'criteria' => json_encode(['vii','ix']),
                'year_inscribed' => 1993,
                'area_hectares' => 10747.0,
                'buffer_zone_hectares' => null,
                'is_endangered' => false,
                'latitude' => null,
                'longitude' => null,
                'short_description' => '巨樹・照葉樹林に代表される生態系と景観が特筆される島。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/662',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 663,
                'official_name' => 'Shirakami-Sanchi',
                'name' => 'Shirakami-Sanchi',
                'name_jp' => '白神山地',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Natural',
                'criteria' => json_encode(['ix','x']),
                'year_inscribed' => 1993,
                'area_hectares' => 16971.0,
                'buffer_zone_hectares' => 6832.0,
                'is_endangered' => false,
                'latitude' => null,
                'longitude' => null,
                'short_description' => '日本最大級のブナ天然林を中心とする山地生態系。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/663',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 1142,
                'official_name' => 'Sacred Sites and Pilgrimage Routes in the Kii Mountain Range',
                'name' => 'Kii Mountain Range',
                'name_jp' => '紀伊山地の霊場と参詣道',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Cultural',
                'criteria' => json_encode(['ii','iii','iv','vi']),
                'year_inscribed' => 2004,
                'area_hectares' => 506.4,
                'buffer_zone_hectares' => 12100.0,
                'is_endangered' => false,
                'latitude' => null,
                'longitude' => null,
                'short_description' => '熊野三山・高野山・吉野・大峯を結ぶ霊場と参詣道の文化的景観。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/1142',
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => 1418,
                'official_name' => 'Fujisan, sacred place and source of artistic inspiration',
                'name' => 'Fujisan',
                'name_jp' => '富士山—信仰の対象と芸術の源泉',
                'country' => 'Japan',
                'region' => 'Asia',
                'state_party' => 'JPN',
                'category' => 'Cultural',
                'criteria' => json_encode(['iii','vi']),
                'year_inscribed' => 2013,
                'area_hectares' => 20702.1,
                'buffer_zone_hectares' => 49627.7,
                'is_endangered' => false,
                'latitude' => null,
                'longitude' => null,
                'short_description' => '日本の象徴たる霊峰。信仰・芸術・登拝文化に深い影響を与えた文化的景観。',
                'image_url' => null,
                'unesco_site_url' => 'https://whc.unesco.org/en/list/1418',
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];
        DB::table('world_heritage_sites')->upsert($sites, ['id']);
    }
}
